name: Dripwire
version: '${project.version}'
main: dripwire.Dripwire
api-version: 1.19
authors: [ mad201802, nlfmt ]
commands:
  spawn:
    description: Teleports you to spawn
    usage: /spawn
  stick:
    description: get a stick
  sethome:
    description: set a home
    usage: /sethome <name>
  delhome:
    description: delete a home
    usage: /delhome <name>
  home:
    description: teleport to a home
    usage: /home <name>
  homes:
    description: list all your homes
    usage: /homes
