name: Dripwire
version: '${project.version}'
main: dripwire.Dripwire
api-version: 1.19
authors: [ mad201802, nlfmt ]
commands:
  spawn:
    description: Teleports you to spawn
    usage: /spawn
  stick:
    description: get a stick
  ping:
    description: Gets the ping of the player
    usage: /ping
  tpa:
    description: Teleports you to the player
    usage: /tpa <player>
  tpaccept:
    description: Accepts the teleport request
    usage: /tpaccept <player>
  tpdeny:
    description: Denies the teleport request
    usage: /tpdeny <player>
  tpcancel:
    description: Cancels the teleport request
    usage: /tpcancel
  sethome:
    description: set a home
    usage: /sethome <name>
    delhome:
      description: delete a home
      usage: /delhome <name>
    home:
      description: teleport to a home
      usage: /home <name>
    homes:
      description: list all your homes
      usage: /homes
