name: Dripwire
version: '${project.version}'
main: dripwire.Dripwire
api-version: 1.19
authors: [ mad201802, nlfmt ]
commands:
  spawn:
    description: Teleports you to spawn
    usage: /spawn
  ping:
    description: Gets the ping of the player
    usage: /ping
